language: go
sudo: required
services:
  - docker
os:
  - linux

go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"

before_install:
# install dependency
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
# build docker image
  - sudo docker build -t pg_gatherer . -f ./docker/test.Dockerfile

install:
  - go get -u -v $(go list -f '{{join .Imports "\n"}}{{"\n"}}{{join .TestImports "\n"}}' ./... | sort | uniq | grep -v gopher-lua-libs)

script:
  sudo docker run --rm -t -i pg_gatherer make test_intergation
