language: go
sudo: required
services:
  - docker
os:
  - linux

go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"

before_install:
# build docker image
  - sudo docker build -t pg_gatherer_test . -f ./docker/test.Dockerfile

script: >
  sudo docker run --privileged -ti --rm --user $(id -u):$(id -g)
  -e TRAVIS=$TRAVIS -e TRAVIS_COMMIT_RANGE=$TRAVIS_COMMIT_RANGE
  -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST -e TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG
  -e TRAVIS_BRANCH=$TRAVIS_BRANCH -e TRAVIS_COMMIT=$TRAVIS_COMMIT
  -v /etc/passwd:/etc/passwd -v /etc/sudoers:/etc/sudoers -v /etc/sudoers.d:/etc/sudoers.d
  pg_gatherer_test bash -c "make test_in_docker"
