language: go
sudo: required
services:
  - docker
os:
  - linux

go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"

before_install:
# build docker image
  - sudo docker build -t pg_gatherer_test . -f ./docker/test.Dockerfile

script: >
  sudo docker run -ti --rm pg_gatherer_test bash -ec "make test_in_docker"
